name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: |
          uv run pytest --cov=src --cov-report=term-missing --cov-report=xml tests/

      - name: Generate coverage badge
        run: |
          uv run genbadge coverage -i coverage.xml -o coverage.svg

      - name: Commit and push badge
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git add coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push origin main
